### ISSUE TITLE
请教关于剪枝时map急剧下降最后变为0的问题

### ISSUE THREAD

**Issue by mengqingyan97** [BokyLiu/YoloV5sl_V4_prune#1]
当我使用自己的数据集进行训练时，基础训练过程和稀疏训练过程均正常，但是进行到剪枝的时候，P，R，map，F1的值急剧下降，剪枝后直接变成0，我想请教您这个问题需要如何解决？
稀疏训练得到的map值是0.7308    P值是0.455    R值是0.8279    F1值是0.3696   
我的数据集一共2059张图片，做火灾识别，classes=1
![image](https://user-images.githubusercontent.com/74995411/120332526-69b8fc00-c321-11eb-9ad9-9d3bdcdcef26.png)

**Comment by BokyLiu** [comment]
有可能啊，一般经过微调精度可以得到恢复

**Comment by mengqingyan97** [comment]
![QQ图片20210603192426](https://user-images.githubusercontent.com/74995411/120638038-36ea4180-c4a2-11eb-9c30-d43691f2408e.png)
![QQ图片20210603192431](https://user-images.githubusercontent.com/74995411/120638049-39e53200-c4a2-11eb-9032-572784ae3716.png)
您好，我稀疏训练后得到的BN权重如图所示，和tanluren/yolov3-channel-and-layer-pruning上的完全不同，请问造成这个问题的原因是什么？是我稀疏训练的不够吗？还是我稀疏训练过程的参数设置有问题？我稀疏训练和基础训练都是100epoch，稀疏训练中s=0.001，prune=1

**Comment by BokyLiu** [comment]
可以改一下s和lr，看你训练过程中直方图没什么变化啊
