### ISSUE TITLE
请教一下关于step3模型剪枝的问题

### ISSUE THREAD

**Issue by 15050188022** [BokyLiu/YoloV5sl_V4_prune#2]
剪枝时总会遇到图中的bug，不知道是不是我的数据格式不对。请问这里的.data文件要怎么设置，数据集格式是否还是yolov5的格式？
![image](https://user-images.githubusercontent.com/30464411/120770479-c2baa700-c550-11eb-8b65-bc4044a985dd.png)

**Comment by BokyLiu** [comment]
还是yolov5的格式

**Comment by 15050188022** [comment]
> 还是yolov5的格式

这是我根据自己的数据集修改的.data文件，别的步骤都是根据你仓库里的来的，step1跟step2也没有问题，但step3时还是会在check_dataset(data)这一行报错，能不能请您帮我看一下是不是.data有什么问题
![image](https://user-images.githubusercontent.com/30464411/120952631-02b2a180-c77e-11eb-8e51-487b3441b154.png)

**Comment by BokyLiu** [comment]
> 剪枝时总会遇到图中的bug，不知道是不是我的数据格式不对。请问这里的.data文件要怎么设置，数据集格式是否还是yolov5的格式？
> ![image](https://user-images.githubusercontent.com/30464411/120770479-c2baa700-c550-11eb-8b65-bc4044a985dd.png)

这个我也看不出来啊，建议你把dict打印出来，再顺着代码逻辑找找出问题的地方。dict应该是字典，在你这不知为何变成了string
